### ISSUE TITLE
support for 'rotated_ll' in GRID_TYPES

### ISSUE THREAD

**Issue by brancomat** [ecmwf/skinnywms#11]
It would be great to have support for `rotated_ll` grid types.

Example grib attached:  
[2t.tar.gz](https://github.com/ecmwf/skinnywms/files/3658682/2t.tar.gz)

**Comment by sylvielamythepaut** [comment]
Hi, 
I have added a temporary fix to support rotated_ll, I think that for now we do not really need this information, we may use it later for a cache. 
I could now see your data, Could you confirm that the geo-referencement is OK ? 
If not, we will open an issue on Magics, since Magics should be able to visualise this kind of representation.

Sylvie

**Comment by brancomat** [comment]
I tested your forked project (https://github.com/sylvielamythepaut/skinnywms) that contains the fix and so far so good. Once the fix is merged we can close this issue. Thank you!

**Comment by sylvielamythepaut** [comment]
Great, I will push the fix on master
Sylvie

**Comment by sylvielamythepaut** [comment]
#13
